<?php
ini_set('xdebug.var_display_max_depth', 10);
ini_set('xdebug.var_display_max_children', 256);
ini_set('xdebug.var_display_max_data', 2024);
//$json = '{"PriceCategories":[{"Availability":{"SoldOut":false,"StatusCode":"Ok"},"PriceCategoryId":1,"PriceCategoryCode":"1","PriceCategoryName":"General Admission"},{"Availability":{"SoldOut":false,"StatusCode":"Ok"},"PriceCategoryId":2,"PriceCategoryCode":"2","PriceCategoryName":"Reserved"}]}';
$json = '{"PriceCategories":[{"PriceCategoryId":1,"PriceCategoryCode":"1","PriceCategoryName":"General Admission"},{"PriceCategoryId":2,"PriceCategoryCode":"2","PriceCategoryName":"Reserved"}],"PriceTypes":[{"PriceTypeId":1,"PriceTypeCode":"H","PriceTypeName":"HOLD ","PriceTypeDescription":"Event Lab Hold","PriceSheetId":0,"AdmitCount":1,"ConcessionCount":0,"OfferCode":"","QualifierCode":null,"Entitlement":null},{"PriceTypeId":2,"PriceTypeCode":"C","PriceTypeName":"COMP ","PriceTypeDescription":"Complimentary","PriceSheetId":0,"AdmitCount":1,"ConcessionCount":0,"OfferCode":"","QualifierCode":null,"Entitlement":null},{"PriceTypeId":3,"PriceTypeCode":"Q","PriceTypeName":"ELAB","PriceTypeDescription":"Event Lab","PriceSheetId":0,"AdmitCount":1,"ConcessionCount":0,"OfferCode":"","QualifierCode":null,"Entitlement":null}],"BasketPrices":null,"TicketPrices":{"Prices":[{"PriceId":1,"PriceCategoryId":1,"PriceCategoryCode":"1","PriceTypeId":1,"PriceTypeCode":"H","PriceSheetId":0,"PriceNet":0,"FeeTypes":null},{"PriceId":2,"PriceCategoryId":2,"PriceCategoryCode":"2","PriceTypeId":1,"PriceTypeCode":"H","PriceSheetId":0,"PriceNet":0,"FeeTypes":null},{"PriceId":3,"PriceCategoryId":1,"PriceCategoryCode":"1","PriceTypeId":2,"PriceTypeCode":"C","PriceSheetId":0,"PriceNet":0,"FeeTypes":null},{"PriceId":4,"PriceCategoryId":2,"PriceCategoryCode":"2","PriceTypeId":2,"PriceTypeCode":"C","PriceSheetId":0,"PriceNet":0,"FeeTypes":null},{"PriceId":5,"PriceCategoryId":1,"PriceCategoryCode":"1","PriceTypeId":3,"PriceTypeCode":"Q","PriceSheetId":0,"PriceNet":10000,"FeeTypes":null},{"PriceId":6,"PriceCategoryId":2,"PriceCategoryCode":"2","PriceTypeId":3,"PriceTypeCode":"Q","PriceSheetId":0,"PriceNet":20000,"FeeTypes":null}],"FeeTypes":null},"OfferPrices":{"Prices":null,"FeeTypes":[{"FeeType":"5","FeeTypeName":"Handling Fee","Inside":false,"FeeBucket":"hfee","FeesDetailed":[{"FeeId":"1","FeeSheetId":0,"FeeCode":"W","FeeName":"WebServ","FeeDescription":"Web Service - API","FeeTotal":0.0,"FinanceCode":null}]}]}}';
$res_obj = json_decode($json);
var_dump($res_obj);
//var_dump(count($res_obj->PriceCategories));
//var_dump($res_obj->PriceCategories[0]);
?>